export interface FolderQuoteItem {
    id: string;
    tabLabel: string;
    bgColor: string;
    textColor: string;
    quote: string;
    author: string;
    handle: string;
    codeRef?: string;
    dateStr?: string;
    tabLeftOffset: number;
}

export const ALL_QUOTE_SETS: FolderQuoteItem[][] = [
    [
        {
            id: "q1",
            tabLabel: "Claude",
            bgColor: "#F472B6",
            textColor: "#111827",
            quote: "Happiness is not something readymade. It comes from your own actions.",
            author: "Dalai Lama",
            handle: "@dalailama",
            codeRef: "16B",
            dateStr: "Dec 13, 1956",
            tabLeftOffset: 0,
        },
        {
            id: "q2",
            tabLabel: "Aiko",
            bgColor: "#818CF8",
            textColor: "#FFFFFF",
            quote: "Write it on your heart that every day is the best day in the year.",
            author: "Ralph Waldo Emerson",
            handle: "@emerson",
            codeRef: "18E",
            dateStr: "Jan 24, 1962",
            tabLeftOffset: 70,
        },
        {
            id: "q3",
            tabLabel: "Perplexity",
            bgColor: "#FFFFFF",
            textColor: "#0F172A",
            quote: "You have power over your mind - not outside events. Realize this, and you will find strength.",
            author: "Marcus Aurelius",
            handle: "@aurelius",
            codeRef: "04A",
            dateStr: "Nov 09, 1974",
            tabLeftOffset: 170,
        },
        {
            id: "q4",
            tabLabel: "Limitless",
            bgColor: "#3B82F6",
            textColor: "#FFFFFF",
            quote: "What you do today can improve all your tomorrows.",
            author: "Ralph Marston",
            handle: "@marston",
            codeRef: "22D",
            dateStr: "Apr 15, 1988",
            tabLeftOffset: 250,
        },
        {
            id: "q5",
            tabLabel: "ChatGPT",
            bgColor: "#D4FE00",
            textColor: "#111827",
            quote: "Design should dominate things, not dominate people.",
            author: "Dieter Rams",
            handle: "@dieterrams",
            codeRef: "15C",
            dateStr: "Mar 18, 1966",
            tabLeftOffset: 0,
        },
    ],
    [
        {
            id: "q6",
            tabLabel: "Claude",
            bgColor: "#F472B6",
            textColor: "#111827",
            quote: "Design is not just what it looks like and feels like. Design is how it works.",
            author: "Steve Jobs",
            handle: "@stevejobs",
            codeRef: "08F",
            dateStr: "Oct 05, 1997",
            tabLeftOffset: 0,
        },
        {
            id: "q7",
            tabLabel: "Aiko",
            bgColor: "#818CF8",
            textColor: "#FFFFFF",
            quote: "You can't use up creativity. The more you use, the more you have.",
            author: "Maya Angelou",
            handle: "@angelou",
            codeRef: "11A",
            dateStr: "May 20, 1978",
            tabLeftOffset: 70,
        },
        {
            id: "q8",
            tabLabel: "Perplexity",
            bgColor: "#FFFFFF",
            textColor: "#0F172A",
            quote: "Turn your wounds into wisdom.",
            author: "Oprah Winfrey",
            handle: "@oprah",
            codeRef: "09C",
            dateStr: "Sep 12, 1985",
            tabLeftOffset: 170,
        },
        {
            id: "q9",
            tabLabel: "Limitless",
            bgColor: "#3B82F6",
            textColor: "#FFFFFF",
            quote: "In the middle of difficulty lies opportunity.",
            author: "Albert Einstein",
            handle: "@einstein",
            codeRef: "21B",
            dateStr: "Jul 04, 1945",
            tabLeftOffset: 250,
        },
        {
            id: "q10",
            tabLabel: "ChatGPT",
            bgColor: "#D4FE00",
            textColor: "#111827",
            quote: "Simplicity is the ultimate sophistication.",
            author: "Leonardo da Vinci",
            handle: "@davinci",
            codeRef: "03E",
            dateStr: "Feb 14, 1968",
            tabLeftOffset: 0,
        },
    ],
    [
        {
            id: "q11",
            tabLabel: "Claude",
            bgColor: "#F472B6",
            textColor: "#111827",
            quote: "Peace comes from within. Do not seek it without.",
            author: "Buddha",
            handle: "@buddha",
            codeRef: "30A",
            dateStr: "Jun 30, 1950",
            tabLeftOffset: 0,
        },
        {
            id: "q12",
            tabLabel: "Aiko",
            bgColor: "#818CF8",
            textColor: "#FFFFFF",
            quote: "The secret of getting ahead is getting started.",
            author: "Mark Twain",
            handle: "@marktwain",
            codeRef: "07D",
            dateStr: "Aug 19, 1910",
            tabLeftOffset: 70,
        },
        {
            id: "q13",
            tabLabel: "Perplexity",
            bgColor: "#FFFFFF",
            textColor: "#0F172A",
            quote: "A journey of a thousand miles begins with a single step.",
            author: "Lao Tzu",
            handle: "@laotzu",
            codeRef: "19K",
            dateStr: "Dec 01, 1972",
            tabLeftOffset: 170,
        },
        {
            id: "q14",
            tabLabel: "Limitless",
            bgColor: "#3B82F6",
            textColor: "#FFFFFF",
            quote: "Luck is what happens when preparation meets opportunity.",
            author: "Seneca",
            handle: "@seneca",
            codeRef: "14X",
            dateStr: "Mar 23, 1960",
            tabLeftOffset: 250,
        },
        {
            id: "q15",
            tabLabel: "ChatGPT",
            bgColor: "#D4FE00",
            textColor: "#111827",
            quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
            author: "Aristotle",
            handle: "@aristotle",
            codeRef: "27N",
            dateStr: "Oct 18, 1982",
            tabLeftOffset: 0,
        },
    ],
];
