/**
 * journal.types.ts - Type Definitions for Journaling
 * 
 * Defines data structures used across the journal creation, storage, and display flows.
 */

export interface JournalEntry {
  /** Unique identifier for the journal entry (typically timestamp string) */
  id: string;
  /** Entry date in YYYY-MM-DD format (used for calendar and timeline lookups) */
  date: string;
  /** User-provided title for the entry */
  title: string;
  /** Rich-text HTML content generated by the Quill editor */
  content: string;
  /** Category tag assigned to the entry (e.g. 'Grateful', 'Calm', 'Anxious', 'Stressful') */
  tag: string;
  /** Full ISO timestamp when the entry was created */
  createdAt: string;
}
